services:
  - postgresql
before_script:
  - psql -c 'create database postgres;' -U postgres
language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
after_success: npm run coverage