language: node_js
node_js: 
  - "stable"
services:
- postgresql
env:
  global:
- JWT_SECRET ='niyitangasamueldoingandelachallenge'
before_script:
- psql -c 'create database politico;' -U postgres
- psql -c "CREATE USER root WITH PASSWORD 'password';" -U postgres
cache:
  directories:
    - "node_modules"
after_success: npm run coverage